### PR TITLE
feat(API): Adding support for passing a template string

### PR DESCRIPTION
**Pull request by KerryRitter**
With the API, I'd like to be able to pass a template string in without having to read it from a file.

### CODE REVIEW

**Comment by mikkotikkanen** [comment]
This seems like a valid thing to have. In fact, now that I think of it, the CLI probably should have done all the file loading and pass only strings to the API. Duh. Well, this might be due for refactoring anyways down the line. 

image

There are few ESLint errors to handle (the first one is just about having ternaries in parenthesis and latter ones are quite self explanatory. For some reason it looks like those aren't currently run for the pull request automatically.

Also, if you could add test for creating and updating the stacks with the strings (something like `/create-stack-string-template.js`) so that we cover that as well. I think you can use the existing template file, just load it with `readSync` and pass it as a string.

**Comment by KerryRitter** [comment]
Gotcha! I should have dug a little deeper on linting and tests :) I'll get this cleaned up.

**Comment by mikkotikkanen** [comment]
Just FYI, merging npm update PR #17 which also updates `eslint-config-airbnb-base` which might cause new ESLint alerts after merged from master

**Comment by KerryRitter** [comment]
Okay, I think I fixed it up! The linter is really mad that I'm on Windows (a bunch of CRLF vs LF errors) but I think I got it?

**Comment by mikkotikkanen** [comment]
If you install editorconfig extensions to whatever editor you are using, it should use correct line endings automatically according `.editorconfig` file. Something is still wrong with the pull request test checks, I'll try to figure those out as soon as I can. Could you also replicate the create-stack test to update-stack as well so we got all bases covered. After that, it looks good to go to me. 👍

**Pull request merged**
